export const SPLINE_COMPLEXITY_WEIGHT_MULTIPLIER = 1.5;

export const CLOSED_SPLINE_COMPLEXITY_MULTIPLIER = 1.2;

export const MAX_SPLINE_TESSELLATION_SAMPLES = 200;

export const MAX_ADAPTIVE_TESSELLATION_SAMPLES = 500;

export const STANDARD_TESSELLATION_TIMEOUT_MS = 5000;

export const HIGH_COMPLEXITY_TIMEOUT_MS = 10000;

export const TESSELLATION_SAMPLE_MULTIPLIER = 3;
