<script lang="ts">
	import { appState } from '$lib/stores.svelte.js';

	let gcode = $state('');
	let isGenerating = $state(false);

	function generateGcode() {
		isGenerating = true;
		
		// Simulate G-code generation
		setTimeout(() => {
			gcode = generateLinuxCNCGcode();
			isGenerating = false;
		}, 1000);
	}

	function generateLinuxCNCGcode(): string {
		const { material, cutPaths } = appState.project;
		
		if (!material || cutPaths.length === 0) {
			return '; No cut paths available\n; Please configure material and generate cut paths first';
		}

		// Basic LinuxCNC QtPlasmaC G-code template
		const header = `; Generated by CAM OCCT
; Material: ${material.name}
; Thickness: ${material.thickness}mm
; Cut Height: ${material.cutHeight}mm
; Feed Rate: ${material.feedRate}mm/min

G21 ; Set units to millimeters
G90 ; Absolute positioning
G94 ; Feed rate mode (units per minute)
M3 S1 ; Turn on plasma cutter
`;

		const body = cutPaths.map((path, index) => `
; Cut Path ${index + 1}
G0 Z${material.cutHeight + 5} ; Move to clearance height
G0 X0 Y0 ; Move to start position
G1 Z${material.cutHeight} F500 ; Pierce height
M3 S1 ; Start cut
G4 P0.5 ; Pierce delay
G1 F${path.feedRate} ; Set cut feed rate
; TODO: Add actual cut path coordinates here
G1 X10 Y0
G1 X10 Y10
G1 X0 Y10
G1 X0 Y0
M5 ; Stop plasma
G0 Z${material.cutHeight + 5} ; Retract to clearance
`).join('');

		const footer = `
; End program
M5 ; Turn off plasma cutter
G0 Z25 ; Move to safe height
M30 ; End program
`;

		return header + body + footer;
	}

	function downloadGcode() {
		const blob = new Blob([gcode], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${appState.project.name || 'output'}.ngc`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}
</script>

<div class="export-page">
	<h2>Export G-code</h2>
	
	<div class="content">
		<div class="controls-panel">
			<div class="card">
				<h3>Export Settings</h3>
				
				<div class="project-info">
					<p><strong>Project:</strong> {appState.project.name}</p>
					{#if appState.project.material}
						<p><strong>Material:</strong> {appState.project.material.name}</p>
						<p><strong>Thickness:</strong> {appState.project.material.thickness}mm</p>
					{/if}
					<p><strong>Cut Paths:</strong> {appState.project.cutPaths.length}</p>
				</div>

				<div class="actions">
					<button 
						class="btn" 
						onclick={generateGcode}
						disabled={isGenerating || appState.project.cutPaths.length === 0}
					>
						{isGenerating ? 'Generating...' : 'Generate G-code'}
					</button>
					
					{#if gcode}
						<button class="btn" onclick={downloadGcode}>
							Download G-code File
						</button>
					{/if}
				</div>

				{#if appState.project.cutPaths.length === 0}
					<div class="warning">
						<p>⚠️ No cut paths available. Please go back to the Program stage and generate cut paths first.</p>
					</div>
				{/if}
			</div>
		</div>

		<div class="preview-panel">
			<div class="card">
				<h3>G-code Preview</h3>
				
				{#if gcode}
					<textarea 
						readonly 
						value={gcode}
						class="gcode-preview"
					></textarea>
				{:else}
					<div class="no-gcode">
						<p>Click "Generate G-code" to preview the output</p>
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>

<style>
	.export-page {
		max-width: 1200px;
		margin: 0 auto;
	}

	.export-page h2 {
		margin-bottom: 2rem;
	}

	.content {
		display: grid;
		grid-template-columns: 1fr 2fr;
		gap: 2rem;
	}

	.project-info {
		background: #f8f9fa;
		padding: 1rem;
		border-radius: 6px;
		margin-bottom: 1rem;
	}

	.project-info p {
		margin: 0.5rem 0;
	}

	.actions {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.warning {
		background: #fff3cd;
		border: 1px solid #ffeaa7;
		border-radius: 6px;
		padding: 1rem;
		margin-top: 1rem;
	}

	.warning p {
		margin: 0;
		color: #856404;
	}

	.gcode-preview {
		width: 100%;
		height: 400px;
		font-family: 'Courier New', monospace;
		font-size: 12px;
		padding: 1rem;
		border: 1px solid var(--border-color);
		border-radius: 4px;
		background: #f8f9fa;
		resize: vertical;
	}

	.no-gcode {
		text-align: center;
		color: #666;
		font-style: italic;
		padding: 2rem;
	}
</style>